exclude: &exclude_patterns |
  (?x)^(
    .*\.hdf5|
    .*\.h5|
    .*\.npy|
    .*\.npz|
    .*\.pkl|
    .*\.pickle|
    .*\.json|
    .*\.csv|
    .*\.dat|
    .*\.mat|
    .*\.yaml|
    .*\.yml|
    applications/q0/calibrations/.*|
    applications/q0/data/.*|
    tests/data/.*|
    data/.*
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: *exclude_patterns
      - id: end-of-file-fixer
        exclude: *exclude_patterns
      - id: check-yaml
        exclude: *exclude_patterns
      - id: check-toml
      - id: check-added-large-files
        exclude: *exclude_patterns
      - id: debug-statements
      - id: check-case-conflict

  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        args: [ --line-length=120 ]
        exclude: *exclude_patterns

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [
          # Add any flake8 plugins here
        ]
        args: [
          "--count",
          "--max-complexity=10",
          "--max-line-length=120",
          "--show-source",
          "--statistics",
          "--extend-ignore=E203,W503"
        ]
        exclude: *exclude_patterns